# Generated by Django 4.1.2 on 2023-01-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCornerCordsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100)),
                ('cornerCords', models.JSONField()),
            ],
            options={
                'db_table': 'GPS_CORNER_CORD',
            },
        ),
        migrations.CreateModel(
            name='StoreNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100)),
                ('floorNumber', models.CharField(max_length=100)),
                ('nodes', models.JSONField()),
            ],
            options={
                'db_table': 'NODE_DATA',
            },
        ),
    ]
