# Generated by Django 4.1.2 on 2023-01-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storecornercordsdata_storenodedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storenodedata',
            old_name='floorNumber',
            new_name='floorName',
        ),
    ]
